# Generated by Django 4.2.6 on 2023-10-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu_app', '0002_menuitem_image_categroy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categroy',
            new_name='Category',
        ),
    ]
