# Generated by Django 4.2.6 on 2023-10-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu_app', '0003_rename_categroy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='restaurant_menu_app.menuitem'),
        ),
    ]
