# Generated by Django 4.2.6 on 2023-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu_app', '0005_remove_category_items_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
